spring:
  application:
    name: demo

  data:
    rest:
      base-path: /api
  h2:
    console:
      enabled: true
      settings:
        web-admin-password: password

  datasource:
    url: jdbc:h2:mem:payrolldb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


#logging:
#  level:
#    root: debug
