spring:
  application:
    name: vault-config
  cloud.vault:
    host: localhost
    port: 8200
    scheme: http
    uri: http://localhost:8200
    connection-timeout: 5000
    read-timeout: 15000
    authentication: TOKEN
#    token: 00000000-0000-0000-0000-000000000000
    token: s.HgWO37R8YSbczAPXCtunS7OT
  config:
    import: vault://