version: "3.7"

services:
  redis:
    container_name: redis
    image: "bitnami/redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes


volumes:
  redis-data: