apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: greeter
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/quarkus-quickstarts/getting-started-knative
          livenessProbe:
            httpGet:
              path: /health/live
          readinessProbe:
            httpGet:
              path: /health/ready
